server:
  port:9091
spring:
  application:
    name: GREET-API  # Change according to your microservice name
  boot:
    admin:
      client:
        url: http://localhost:1111  # Admin Server URL
       
  zipkin:
    base-url: http://localhost:9411/  # Zipkin Server URL
  cloud:
    discovery:
      enabled: true  # Ensure Eureka discovery is enabled

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always  # Ensure detailed health status
  tracing:
    sampling:
      probability: 1.0  # Full tracing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
  instance:
    prefer-ip-address: true  
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
